apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m               
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "7.17.0"
  values:
    adminUser: admin
    adminPassword: admin
    service:
      type: ClusterIP
      port: 3000
    ingress:
      enabled: true
      hosts:
        - host: app-monitor.local
          paths:
            - /
      annotations:
        kubernetes.io/ingress.class: nginx
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
