apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m           
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      version: "5.11.0"
  values:
    persistence:
      enabled: true
      size: 10Gi
    service:
      type: ClusterIP
