apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
    namespace: wordpress
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:JSrmOQ==,iv:4IOjIKe+xuVlwnrKVSVU1L6kiRi1OJ/spTgS+ZayWHw=,tag:ZFj8SJJdwNfrMBuZtiIcvQ==,type:str]
    password: ENC[AES256_GCM,data:3u2/toFtz2BF14Q=,iv:T3z8pgud90HK8xzfHlpES69UldMtC2f8qZDaY7Wv9p4=,tag:Bxz/AOen8SQC5bD91HbMIQ==,type:str]
    database: ENC[AES256_GCM,data:XOHCr+4F/+Gd,iv:7ZRCaQxMl7f4sGz6UbKM1ArkEXN85Mys+gG8meOQ3I0=,tag:Us9ino8B8htXaimVIHmstg==,type:str]
sops:
    age:
        - recipient: age1vsh7t60jklcwj86ynj3jyezfc7p3849vsjffmf5m37tnha2sw4asl39csf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5R0N6czNEVEJ3QW11dW5W
            QVUxaE9qRkI0aTVSOGo2ZUpTTzUxM0tab0VrCkkxcTlXT01tZ0hMWlhCSnhNR1Ar
            bTZEREJHRExpeFF0VEJiZEZKd09TczgKLS0tIHZiemEvbkI1T1l5SmZ1dzZYVEhl
            SmhLUWVvT0dWSG0yOWxzMkhhY1NZUEUK187M5BEsfQmoJCqsPXac73BqaDd9dHPg
            EDu1UgC8mZs6kK8ZyFWFYCADl5p9Yv2PTMKzZmNc758eAJOTt2OpeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T09:50:59Z"
    mac: ENC[AES256_GCM,data:J0Qm5ULhRBZBxtuzpDjmM16cmt0D9jBKmD5INWRuU+CQ+yicLDtvQh983AuDG2fpqJEWSJ0nBk7yMYumBPTaiWrA/G94gx2KJ3mgskdKoPSGRpfLyH5rukTPgZ31Qj3LPW96vBJglkkY8fIHXZ0atEne880vAunHx9BsgRXnBtw=,iv:F/vP3WiEd9fFF81nQ41uzxpzLTpif9nF2fBWbFVhy/w=,tag:31JMYz0jv8LlIbXy+kcgcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2